#!/bin/bash
# Vercel Deployment Setup Guide
# This script helps you set up automated deployment to Vercel

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Dashboard → Vercel Auto-Deployment Setup                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "STEP 1: Create Vercel Account & Project"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to https://vercel.com and sign in with GitHub"
echo "2. Click 'Add New' → 'Project'"
echo "3. Select 'wghtkbpxwx-a11y/Grok-model-'"
echo "4. Click 'Deploy'"
echo "5. Wait for deployment to complete"
echo ""
echo "After deployment completes, you'll see your URL:"
echo "  https://grok-model-XXXXX.vercel.app"
echo ""

echo "STEP 2: Get Vercel Tokens"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to https://vercel.com/account/tokens"
echo "2. Click 'Create Token'"
echo "3. Name it 'GitHub Actions'"
echo "4. Copy the token (you'll need it next)"
echo ""

echo "STEP 3: Get Project IDs from Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to your project: https://vercel.com/dashboard"
echo "2. Select your Grok Model project"
echo "3. Go to Settings → General"
echo "4. Copy the 'Project ID'"
echo "5. Go to Settings → General and find 'Team ID' (your org ID)"
echo ""

echo "STEP 4: Add Secrets to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to GitHub: https://github.com/wghtkbpxwx-a11y/Grok-model-"
echo "2. Click Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo ""
echo "Add these secrets:"
echo "  Name: VERCEL_TOKEN"
echo "  Value: [paste token from Step 2]"
echo ""
echo "  Name: VERCEL_ORG_ID"
echo "  Value: [paste Team ID from Step 3]"
echo ""
echo "  Name: VERCEL_PROJECT_ID"
echo "  Value: [paste Project ID from Step 3]"
echo ""

echo "STEP 5: Test the Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to GitHub: https://github.com/wghtkbpxwx-a11y/Grok-model-"
echo "2. Click 'Actions'"
echo "3. You should see 'Deploy to Vercel' workflow"
echo "4. It should show a green checkmark when complete"
echo ""

echo "STEP 6: Update Tesla Browser Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In your Tesla, go to: https://grok-model-XXXXX.vercel.app"
echo "   (Replace XXXXX with your actual project ID)"
echo ""
echo "2. Refresh the page"
echo "3. News, weather, and sports should now load!"
echo ""

echo "✓ Setup complete! Your dashboard now auto-deploys to Vercel."
echo "  Any code changes pushed to main will automatically deploy."
echo ""
